config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists
  get 'home/about' => 'home#about'
  root to: "home#index"
  #root 'home#index'
  #get 'home/index'
  #get "/" => "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
    @todo_list = TodoList.find(params[:id])
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Nami's First App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Me", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ToDo Lists", todo_lists_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Nami's First App...</h1>

app/views/home/index.html.erb
<h1>Welcome to Nami's first webapp!</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nami's First App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  
  <body>
    <%= render "home/header" %>
    <div class="container">
      <br>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed, class:"form-check-input" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">

<div class="card">
  <div class="card-header">
    <h4 class="card-title"><%= todo_list.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= todo_list.description %></p>
  </div>
</div>

</div>

app/views/todo_lists/edit.html.erb
<h1>Editing todo list</h1>
<br>
<%= render "form", todo_list: @todo_list %>

<br>
<div>
  <%= link_to "Show", @todo_list, class:"btn btn-secondary" %>
  <%= link_to "Back", todo_lists_path, class:"btn btn-dark"%>
</div>

app/views/todo_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>ToDo List</h1>

<table class="table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= todo_list.completed %></td>
        <td><%= link_to "Show", todo_list %></td>
        <td><%= link_to "Edit", edit_todo_list_path(todo_list) %></td>
        <td><%= link_to "Destroy", @todo_list, method: :delete %></td> <%# link not working yet%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Add New ToDo List", new_todo_list_path, class:"btn btn-secondary" %>

app/views/todo_lists/new.html.erb
<h1>Add New ToDo List</h1>
<br>
<%= render "form", todo_list: @todo_list %>

<br>
<div>
  <%= link_to "Back", todo_lists_path,
  class:"btn btn-dark" %>
</div>

app/views/todo_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo_list %>
<br>
<div>
  <%= link_to "Edit", edit_todo_list_path(@todo_list), class:"btn btn-secondary" %>
  <%= link_to "Back", todo_lists_path, class:"btn btn-secondary" %>
</div>